replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "stable"

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: nginx-example.local
      paths: ["/"]
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
